//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pub.Model.DWModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DimTitle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DimTitle()
        {
            this.FactSales = new HashSet<FactSales>();
        }
    
        public int TitleKey { get; set; }
        public string TitleId { get; set; }
        public string TitleName { get; set; }
        public string TitleType { get; set; }
        public int PublisherKey { get; set; }
        public decimal TitlePrice { get; set; }
        public int PublishedDateKey { get; set; }
    
        public virtual DimDate DimDate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactSales> FactSales { get; set; }
    }
}
