//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pub.Model.DWModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class FactSales
    {
        public string OrderNumber { get; set; }
        public int OrderDateKey { get; set; }
        public int TitleKey { get; set; }
        public int StoreKey { get; set; }
        public int SalesQuantity { get; set; }
    
        public virtual DimDate DimDate { get; set; }
        public virtual DimTitle DimTitle { get; set; }
        public virtual DimStore DimStore { get; set; }
    }
}
